common: &common
  adapter: postgresql
  username: postgres
  password: admin

development:
  <<: *common
  database: RewardTracker_development

test:
  <<: *common
  database: RewardTracker_test

production:
  <<: *common
  database: RewardTracker_production